- CONTRIBUTING.md
- spack-environments/cosma8/spack.yaml
- spack-environments/csd3/spack.yaml
- spack-environments/dial3/spack.yaml
- spack-environments/github-actions/spack.yaml
- spack-environments/isambard-cascadelake/spack.yaml
- spack-environments/myriad/spack.yaml
- spack-environments/tesseract/spack.yaml
- spack-environments/tursa/spack.yaml
Also, explicitly specify to concretize separately.  Note, that's the default
strategy, so it isn't fundamental to do this, but it's still useful to be
explicit, and also be safe against a change of the default strategy (as unlikely
as that is).
Fix #20
> Disable views in Spack environments

- .github/workflows/ci.yml
- README.md
- examples/sombrero/sombrero.py
- modules/utils.py
- reframe_config.py
This lets us avoid touching the original Spack environment when running the
benchmarks.  The Spack spec can always be customised from the command line and its value will be recorded in the log, for future reference.
> Automatically copy the Spack environment

- apps/imb/imb.py
We should let users customise them with `spack_spec`.
> [imb] Do not hardcode MPI implementations

- reframe_config.py
My understanding of https://www.dur.ac.uk/icc/cosma/support/cosma8/ is that each
node of Cosma8 has two sockets of [64-core AMD EPYC
7H12](https://en.wikichip.org/wiki/amd/epyc/7h12) CPUs, no hyperthreading.
> [cosma8] Fix processor configuration

- spack-environments/archer2/compute-node/spack.yaml
See the individual commits for the changes done.  Main troubles I had for building Grid were
* compiling with gcc and using cray-mpich built with craylang (the fact that the modules have the same names is also a bit confusing)
* Cray wrappers for GCC caused lots of confusion for Spack (more specifically when trying to set `SPACK_COMPILER_IMPLICIT_RPATHS`), using the GCC binaries directly solved the issue
On this branch I was able to build `grid@develop%cce` and `grid@develop%gcc` without problems.
> [archer2] A few changes to the Spack environment

- reframe_config.py
The environment `builtin` doesn't exist anymore, it's called `default` now. This mismatch caused the benchmark not to actually run on CI.
> [CI] Fix ReFrame configuration of GitHub Actions system

- apps/imb/imb.py
- modules/imb.py
While a dataframe is a nicer datastructure for holding the data coming out of the IMB benchmarks, we don't really use dataframes features in any way and this needlessly put a requirement for `pandas` when running the benchmark.  We can easily live with a list of lists, without much effort (actually, with one or two lines less in total)
Fix #47.
> [imb] Avoid using Pandas

- spack-environments/myriad/compute-node/spack.yaml
Note: system `python@3` doesn't seem to be usable by spack because libpython is only found via `LD_LIBRARY_PATH`, not rpath/runpath.
> Expand spack environment for Myriad

- spack-environments/common.yaml
This forces to always use packages already available in the environment.
> [Spack] Make MPI packages not buildable

- spack-environments/myriad/compute-node/spack.yaml
`gettext` is missing the library `libintl.so`, `texinfo` is missing the executable `makeinfo`, it is not possible to correctly use these packages with these missing bits.
> Remove incomplete system packages from Myriad Spack environment

- spack-environments/archer2/compute-node/spack.yaml
- spack-environments/common.yaml
- spack-environments/cosma8/compute-node/spack.yaml
- spack-environments/csd3-icelake/compute-node/spack.yaml
- spack-environments/csd3-skylake/compute-node/spack.yaml
- spack-environments/dial3/compute-node/spack.yaml
- spack-environments/github-actions/default/spack.yaml
- spack-environments/isambard-a64fx/compute-node/spack.yaml
- spack-environments/isambard-cascadelake/compute-node/spack.yaml
- spack-environments/myriad/compute-node/spack.yaml
- spack-environments/tesseract/compute-node/spack.yaml
- spack-environments/tursa/cpu/spack.yaml
Unfortunately the root of the install tree seems to be relative to the file where the configuration is written, rather than the main `spack.yaml` file, so it's not really possible to share this option among all configurations.
> [spack] Move `intall_tree` option back to individual files

- CONTRIBUTING.md
- examples/sombrero/sombrero.py
- reframe_config.py
- spack-environments/isambard-xci/compute-node/spack.yaml
I only tested the simple Sombrero example, and that one worked straight away:
```console
> reframe -c examples/sombrero/ -r --performance-report --system isambard-xci
[ReFrame Setup]
version:           3.12.0
command:           '/home/ri-mgiordano/repo/reframe/bin/reframe -c examples/sombrero/ -r --performance-report --system isambard-xci'
launched by:       ri-mgiordano@xcil00
working directory: '/lustre/home/ri-mgiordano/repo/excalibur-tests'
settings file:     '/home/ri-mgiordano/repo/excalibur-tests/reframe_config.py'
check search path: '/lustre/home/ri-mgiordano/repo/excalibur-tests/examples/sombrero'
stage directory:   '/lustre/home/ri-mgiordano/repo/excalibur-tests/stage'
output directory:  '/lustre/home/ri-mgiordano/repo/excalibur-tests/output'
[==========] Running 1 check(s) …
```
> Add Isambard XCI partition

- CONTRIBUTING.md
- spack-environments/archer2/compute-node/spack.yaml
- spack-environments/common.yaml
- spack-environments/cosma8/compute-node/spack.yaml
- spack-environments/csd3-icelake/compute-node/spack.yaml
- spack-environments/csd3-skylake/compute-node/spack.yaml
- spack-environments/dial3/compute-node/spack.yaml
- spack-environments/github-actions/default/spack.yaml
- spack-environments/isambard-a64fx/compute-node/spack.yaml
- spack-environments/isambard-cascadelake/compute-node/spack.yaml
- spack-environments/isambard-xci/compute-node/spack.yaml
- spack-environments/myriad/compute-node/spack.yaml
- spack-environments/tesseract/compute-node/spack.yaml
- spack-environments/tursa/cpu/spack.yaml
While looking into https://github.com/ukri-excalibur/excalibur-tests/pull/85#issuecomment-1429519523 I found the [Spack-specific variable](https://spack.readthedocs.io/en/latest/configuration.html#spack-specific-variables) `$env`, which allows us to reference the path to the active environment in the common file `common.yaml`, so that we can have again the `install_tree` setting in the common file.  This more or less reverts  #75, but now we have better solution.
> [spack] Move `intall_tree` option back to common file

- README.md
- SYSTEMS.md
Ref #46.  I started with ARCHER2 and Myriad, as they are the systems I used most recently, but I will add information about the others as I remember what we need to do there (often need to specify a job queue or user account).
> Add documentation about system-specific details

- spack-environments/common.yaml
`opt/spack` follows the tree structure of the default Spack install tree, but we don't really need to follow it strictly, and we can save 6 characters from the shebang line.
> Shorten path of install tree

- apps/imb/imb.py
We were passing the wrong argument to the `Metric()` function in the MPI benchmark. This PR will fix that and add some helpful comments.
> Fix MPI1 benchmark

- benchmarks/spack/myriad/compute-node/spack.yaml
This makes it possible to run C++ programs, such as `cmake`, built with
compilers newer than the system default one.
> [myriad] Set `LD_LIBRARY_PATH` for all GCC versions

- benchmarks/reframe_config.py
- benchmarks/spack/common.yaml
- benchmarks/spack/myriad/compute-node/spack.yaml
- benchmarks/spack/tursa/gpu/spack.yaml
Note: for simplicity, we're removing the CPU partition from Tursa, as most users will likely want to use the GPU partition on this machine.  We can later bring back the CPU partition if requested.
Taken out of #115.
> Add configuration for GPU nodes on Myriad and Tursa

- README.md
- benchmarks/reframe_config.py
- pyproject.toml
Names were uniformised in ReFrame v4.1.3.  These are the names that are now [documented](https://reframe-hpc.readthedocs.io/en/v4.1.3/config_reference.html#config.logging.handlers_perflog.format_perfvars).
> [reframe] Use new names of performance reference thresholds

- README.md
`RFM_CONFIG_FILE` is deprecated in favour of `RFM_CONFIG_FILES`, and now
`RFM_USE_LOGIN_SHELL` only accepts `true` as value, it used to accept any
non-empty string.
> [README] Update docs for a couple of ReFrame variables

- benchmarks/reframe_config.py
We're already using `extra_resources` for the SGE scheduler, but we may expand its usage in the future, for example starting from #115 we may use it to set the number of GPU devices used, and could later use it for something more, so I think it may be useful to log also this attribute.
> [reframe] Add `extra_resources` attribute to the perflog

- benchmarks/apps/openmm/openmm_rfm.py
- benchmarks/reframe_config.py
- benchmarks/spack/isambard-macs/pascal/spack.yaml
Ref #78.
```console
$ reframe -c benchmarks/apps/openmm/ -r --performance-report --system isambard-macs:pascal -S spack_spec='openmm +cuda ^openblas ^openmpi'
[ReFrame Setup]
version:           4.1.3
command:           '/lustre/home/ri-mgiordano/repo/excalibur-tests/excal-macs/bin/reframe -c benchmarks/apps/openmm/ -r --performance-report --system isambard-macs:pascal -S spack_spec=openmm +cuda ^openblas
^openmpi'
launched by:       ri-mgiordano@login-01
working directory: '/lustre/home/ri-mgiordano/repo/excalibur-tests'
settings files:    '<builtin>', '/home/ri-mgiordano/repo/excalibur-tests/benchmarks/reframe_config.py'
check search path: '/lustre/home/ri-mgiordano/repo/excalibur-tests/benchmarks/apps/openmm'
stage directory:   '/lustre/home/ri-mgiordano/repo/excalibur-tests/stage' …
```
> Add Nvidia Pascal GPU partition on Isambard

- benchmarks/apps/grid/grid.py
- benchmarks/examples/sombrero/sombrero.py
- benchmarks/reframe_config.py
- benchmarks/spack/isambard-macs/knl/spack.yaml
Ref #78
```console
$ reframe -c benchmarks/examples/sombrero -r --performance-report --system isambard-macs:knl -S spack_spec='sombrero@2021-08-16 ^openmpi' -S build_locally=false
[ReFrame Setup]
version:           4.1.3
command:           '/lustre/home/ri-mgiordano/repo/excalibur-tests/excal-macs/bin/reframe -c benchmarks/examples/sombrero -r --performance-report --system isambard-macs:knl -S spack_spec=sombrero@2021-08-16 ^openmpi -S build_locally=false'
launched by:       ri-mgiordano@login-01
working directory: '/lustre/home/ri-mgiordano/repo/excalibur-tests'
settings files:    '<builtin>', '/home/ri-mgiordano/repo/excalibur-tests/benchmarks/reframe_config.py'
check search path: '/lustre/home/ri-mgiordano/repo/excalibur-tests/benchmarks/examples/sombrero'
stage directory: …
```
> Add KNL partition on Isambard

- .github/workflows/ci.yml
In ReFrame 4 this is now called `RFM_CONFIG_FILES`.
> [CI] Rename `RFM_CONFIG_FILE` environment variable

- benchmarks/apps/cp2k/cp2k.py
- benchmarks/apps/grid/grid.py
- benchmarks/apps/hpgmg/hpgmg.py
- benchmarks/apps/openmm/openmm_rfm.py
- benchmarks/apps/sombrero/sombrero.py
- benchmarks/apps/swift/swift.py
- benchmarks/apps/wrf/wrf.py
- benchmarks/examples/sombrero/sombrero.py
- benchmarks/modules/utils.py
In the same vein as #137, further reduction of boilerplate code.
I need to double check this on Myriad, which is currently down, but I'm mostly confident this works as expected.
> Set `self.extra_resources` directly in base `SpackTest` class

- benchmarks/apps/openmm/openmm_rfm.py
- benchmarks/reframe_config.py
This lets us distinguish systems with Nvidia GPUs from those with AMD GPUs.
CC: @kaanolgu.
> Add `cuda` feature to config of systems with Nvidia GPUs

- benchmarks/examples/sombrero/sombrero.py
- benchmarks/reframe_config.py
- benchmarks/spack/isambard-phase3/compilers.yaml
- benchmarks/spack/isambard-phase3/milan/spack.yaml
- benchmarks/spack/isambard-phase3/packages.yaml
Ref #78.
~Opening as draft as I still haven't figured out how to make compilation of MPI programs work properly.~
```console
$ reframe -c benchmarks/examples/sombrero -r --performance-report --system isambard-phase3:milan
[ReFrame Setup]
version:           4.1.3
command:           '/lustre/home/ri-mgiordano/repo/excalibur-tests/excal-p3/bin/reframe -c benchmarks/examples/sombrero -r --performance-report --system isambard-phase3:milan'
launched by:       ri-mgiordano@p3-login
working directory: '/lustre/home/ri-mgiordano/repo/excalibur-tests'
settings files:    '<builtin>', '/lustre/home/ri-mgiordano/repo/excalibur-tests/benchmarks/reframe_config.py'
check search path: '/lustre/home/ri-mgiordano/repo/excalibur-tests/benchmarks/examples/sombrero'
stage directory: …
```
> Add Milan CPU partition on Isambard Phase 3

- benchmarks/reframe_config.py
After encountering the following error message, I checked the `reframe-config.py` file and found a missing letter in the name
```
$ reframe -c benchmarks/apps/babelstream -r --tag hip --system=isambard-phase3:instinct -S build_locally=false -S spack_spec='babelstream@develop%gcc@9.2.0 +rocm amdgpu_target=gfx908'
ERROR: failed to load configuration: could not find a configuration entry for the requested system/partition combination: 'isambard-phase3:instinct'
Log file(s) saved in '/tmp/rfm-fn32usc9.log'
```
> Name Fix for Isambard Phase 3 Instinct System

- benchmarks/spack/cosma8/compute-node/spack.yaml
The main problem was that the compiler itself links to `libimf.so` (Intel Math Library) and relies on `LD_LIBRARY_PATH` being set correctly for the dynamic loader to find it at runtime.  Likewise, the compiler generates binaries which link to `libimf.so` without setting rpath/runpath, and so `LD_LIBRARY_PATH` would be needed again to use those binaries.
The solution was to update the compiler settings in the spack environment to add the directory where `libimf.so` is to `LD_LIBRARY_PATH`, to make the compiler work in the first place, _and_ to list the same directory as an additional rpath to set when linking objects with oneAPI toolchains.
Fix #155.  ~I can't currently run benchmarks with reframe, but~ building of `sombrero%oneapi@2021.1` and `sombrero%oneapi@2021.3.0` worked successfully …
> [cosma8] Fix oneAPI compiler settings in Spack environment

- benchmarks/modules/utils.py
Error introduced in #139, but I could test it only today.  Glorified comments aka type hinting strikes again.
> Fix setting of `num_slots` resources for SGE scheduler

- benchmarks/spack/repo/packages/hpcg_excalibur/package.py
Ref: https://github.com/ukri-excalibur/excalibur-tests/pull/157#discussion_r1200754814.  I had a quick look at the code of hpcg and I couldn't see _**anything**_ specific to OpenMPI.  I ran this branch on Myriad with Intel MPI + Intel compiler:
```
$ reframe -c benchmarks/apps/hpcg/ -r --performance-report --system myriad:cpu --name HPCG_Stencil -S spack_spec='hpcg_excalibur@hpcg_stencil%intel ^intel-mpi'
[...]
PERFORMANCE REPORT
---------------------------------------------------------------------------
[HPCG_Stencil /21b95432 @myriad:cpu:default]
num_tasks_per_node: 36
num_tasks: 36
num_cpus_per_task: 1
performance:
- flops: 37.9305 Gflops/seconds (r: 1 Gflops/seconds l: -inf% u: +inf%)
---------------------------------------------------------------------------
```
> [hpcg] Allow building with any MPI implementation

- benchmarks/spack/cosma8/compute-node/spack.yaml
- benchmarks/spack/csd3-skylake/compute-node/spack.yaml
Remove unusable `intel@19.0.4.243`, compilation using this compiler fails with
```
>> 95     icpc: error #10408: The Intel LLVM Based compiler cannot be found i
n the expected location.  Please check your installation or documen
tation for more information.
>> 96     /usr/local/Cluster-Apps/intel/2019.4/compilers_and_libraries_2019.4
.243/linux/bin/intel64/icx: No such file or directory
```
I successfully ran the babelstream benchmark with
```
reframe -c benchmarks/apps/babelstream -r --system csd3-skylake:compute-node --job-option='--account=...' -S spack_spec='babelstream%intel@XXX +omp' --tag omp
```
for all versions of the Intel compilers on CSD3 (after removing one that was unusable).
Fix #173
> [csd3-skylake] Fix settings of Intel compilers for building Babelstream

- SYSTEMS.md
These were still referring to the old paths before changing the layout of the repository.
> Fix sample code in `SYSTEMS.md` file

- README.md
This is no longer needed and this line can create confusion.
> Remove reference to installing ReFrame manually

- benchmarks/examples/sombrero/sombrero.py
This gets rid of failures in the sombrero example because of too low performance numbers on Archer2.
> Remove lower bound to avoid issues during tutorial

- benchmarks/apps/wrf/wrf.py
- benchmarks/modules/utils.py
I tested locally with the Sombrero benchmark and it seems to be doing the job, the file `spack.lock` is preserved in the output directory together with the other log files.
Note: in the benchmarks we should always append to `self.keep_files`, instead of forcibly overwriting its value. 
Fix #210.
> Keep `spack.lock` file after a successful benchmark finishes

- .github/dependabot.yml
- .github/workflows/ci.yml
* Use Dependabot to update CI workflows
* Set `RFM_CONFIG_FILES` once for the entire build
* Update `actions/checkout` to v4
* Clone Spack with `--depth=1`
* No need to reference `$Python_ROOT_DIR` for running the benchmarks
> Some improvements to CI setup

- benchmarks/apps/sombrero/sombrero.py
Address https://github.com/ukri-excalibur/excalibur-tests/issues/237#issue-2010042384.  @mirenradia Can you please check this solves the issues you reported in the first post?
> [sombrero] Simplify classes used in benchmarks

- benchmarks/apps/sombrero/README.md
- benchmarks/apps/sombrero/sombrero.py
Should fix https://github.com/ukri-excalibur/excalibur-tests/issues/237#issuecomment-1827595717.  I followed the suggestion in https://github.com/ukri-excalibur/excalibur-tests/issues/237#issuecomment-1828323882.  Probably this isn't the most efficient algorithm out there, but this takes a bunch of microseconds on my laptop, so hopefully it won't be a major performance bottleneck:
```
In [7]: %%timeit
...: max_num_tasks(112, LATTICE_VOLUME)
...: 
...: 
3.75 µs ± 24.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```
CC: @mirenradia.
> [sombrero] Handle systems where number of cores doesn't divide lattice volume

- post-processing/README.md
- post-processing/post_processing.py
- post-processing/post_processing_config.yaml
- post-processing/test_post_processing.py
- pyproject.toml
> Add data transformations for post-processing plot data

- post-processing/post_processing.py
Change `df[col].apply(lambda x: ast.literal_eval(x))` to either `df[col].apply(lambda x: ast.literal_eval(x.replace('null', 'None')))` or `df[col].apply(lambda x: json.loads(x))`, otherwise the current code throws `ValueError: malformed node or string` when the dict contents of `extra_resources` or `env_vars` contain a null.
> Fix perflog parsing with dictionary fields containing null

- post-processing/config_handler.py
- post-processing/perflog_handler.py
- post-processing/plot_handler.py
- post-processing/post_processing.py
- post-processing/test_post_processing.py
> Refactor post-processing

- post-processing/config_handler.py
- post-processing/post_processing.py
- post-processing/streamlit_post_processing.py
> Activate filters and series in Streamlit UI for post-processing

- benchmarks/modules/utils.py
- benchmarks/reframe_config.py
@kaanolgu can you please check this works for you?  If I remember correctly, we need to define the `extra_resource` so that it's applied in the configuration, but in this case we don't need (yet?) to define any custom variable, so I think an empty dictionary should work?
> Create resource group to apply memory setting for Isambard Instinct

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/docs_cleanup.yml
* Run jobs only when relevant files are touched
* Set lower timeout for all jobs, to avoid rogue jobs to run needlessly for
hours
* Set concurrency groups, to cancel jobs if there are new commits on the same
branch
* More informative message for commits pushing docs preview
* Push documentation only on pushes to `main`
> Various improvements to the CI setup

- .github/workflows/docs.yml
In #294 I noticed that the links in the main page (coming from the top-level `README.md`) of the docs preview were pointing to the "production" website, not the preview one, because of course if the Markdown files have any links they'd point to the production version.  With this step we should be able to automatically rewrite the links, so as to keep them within the preview docs.
***Edit***: to confirm this works, see how the links in the [Documentation](https://ukri-excalibur.github.io/excalibur-tests/preview/PR295/#documentation) section now point to pages within the preview.
> [docs] Rewrite URLs in Markdown files for docs previews

- .github/workflows/ci.yml
- docs/install.md
> Update spack version in CI and add note in docs

- .github/workflows/docs.yml
If we rewrite the hyperlinks in symlinked files we risk to accidentally append duplicate `${PREVIEW_SUBDIR}`, depending on the order with which `find` operates on the files.
Should fix #304.
> [CI] Do not rewrite links in symlinked files

- .github/workflows/docs.yml
I believe with mkdocs
[v1.6.0](https://github.com/mkdocs/mkdocs/releases/tag/1.6.0) we may have to allow empty commits, because the compressed sitemap shouldn't change anymore on every rebuild.
> [CI] Allow empty git commit when deploying docs to gh-pages

- .github/workflows/docs.yml
When building the docs for PRs, were trying to run some code which was only relevant when deploying the docs for PRs not from forks.  Spotted in #311.
> [CI] Fix build of docs from PRs

- benchmarks/spack/cosma7/compilers.yaml
- benchmarks/spack/cosma8/compute-node/spack.yaml
- benchmarks/spack/csd3-centos7/cascadelake/spack.yaml
- benchmarks/spack/csd3-rocky8/compilers.yaml
- benchmarks/spack/dial3/compute-node/spack.yaml
- benchmarks/spack/isambard-phase3/compilers.yaml
> [Spack] Remove old `dpcpp` compiler from all environments

- benchmarks/reframe_config.py
I've ran several benchmarks (Stream, Sombrero, Babelstream) successfully with this. Does it look ok?
I haven't included a spack env because Kacper recommended chaining to the Dawn spack instance. There is a script `/usr/local/dawn/software/spack/spack-tools/bin/spack-dawn-upstream.sh` which does it. I think this is in general a better idea than maintaining our own spack envs. Ideas welcome how to do it in a sustainable way.
> Add ReFrame config for CSD3 Ponte Vecchio (Dawn) partition

- post-processing/test_post_processing.py
- pyproject.toml
Update bokeh version to work with latest numpy
Closes #334
> Require numpy 1 due to incompatibility with Streamlit

- benchmarks/reframe_config.py
* Add comments to improve clarity of all the conditions considered
* There were unnecessary `else` branches
* Cater for the dramatic case where both `SPACK_ROOT` and `PATH` are not set
* Fix the case where `PATH` isn't set but `SPACK_ROOT` is (we were returning the function `dir` before, fun)
* Fix the case where `spack_bindir` isn't in `PATH` (we were using `*` for non-commutative concatenation of strings, it turns out in Python one should use `+` instead for this operation)
> Some changes to `spack_root_to_path`

- benchmarks/modules/utils.py
Add double escape to silence warnings in python 3.12
> Fix syntax warning in `setup_spack_environment`

- benchmarks/examples/stream/stream.py
With this PR I was able to run the `stream` example benchmark on my new laptop, the caveat being that I need to manually set `-S num_cpus_per_task=22` on the command line to be able to run with the right number of cores (I tried to follow the [example in the documentation](https://reframe-hpc.readthedocs.io/en/v4.6.3/tutorial.html#accessing-cpu-topology-information) to automatically discover the topology of the system, but the only result was to completely skip the test due to the call to [`skip_if_no_procinfo`](https://reframe-hpc.readthedocs.io/en/v4.6.3/regression_test_api.html#reframe.core.pipeline.RegressionTest.skip_if_no_procinfo))
> [stream] Set number of CPUs/task based on available CPUs

- benchmarks/apps/purify/purify.py
- post-processing/test_post_processing.py
https://github.com/astro-informatics/purify
> Add purify radioastronomy benchmarks

- benchmarks/modules/utils.py
- docs/use.md
- mkdocs.yml
Proof-of-concept for #347, at the moment only supporting vtune.  Everything is up-to-discussion, this is just to show how this could work. 
You can run this for the stream example with
```
reframe -c benchmarks/examples/stream -r --performance-report -S profiler=vtune
```
(the main point is the option `-S profiler=vtune`, the rest are whatever other options you want to pass to `reframe`).
> Automatically run a profiler with the executable

- .github/workflows/ci.yml
- benchmarks/spack/github-actions/default/spack.yaml
I'm a bit torn about how to best fix #359.  I tried [automatically populating the Spack environment](https://github.com/ukri-excalibur/excalibur-tests/commit/4631503010a1389d8b21400335c4b2e9fa468b7c) in every job, which should hopefully always ensure consistency, but [that step can take over a minute](https://github.com/ukri-excalibur/excalibur-tests/actions/runs/13244795136/job/36968533449#step:9:1), depending on the mood of the machine. The solution proposed here (just manually update the environment) is less future-proof, but would avoid wasting time in every job.  I'm happy to change to the other solution if considered preferable.
> [spack] Update environment for GitHub Actions

- benchmarks/reframe_config.py
On isambard-3 jobs were failing when submitting 64 at a time, I've decreased it to a smaller number and it seems to be working.
> reduce max jobs on isambard-3

- benchmarks/spack/kathleen/compute-node/spack.yaml
Compiler wrappers use generic names, let Spack know it so that it can find them correctly.
> [kathleen] Add `+generic-names` to `intel-oneapi-mpi`

- .github/workflows/ci.yml
- benchmarks/spack/cosma8/compute-node/spack.yaml
- benchmarks/spack/csd3-centos7/cascadelake/spack.yaml
- benchmarks/spack/github-actions/default/spack.yaml
- benchmarks/spack/tursa/gpu/spack.yaml
Spack v1.0 will parse `pkg %gcc +foo` as "pkg with direct dependency gcc
with variant foo enabled" instead of "pkg with variant foo enabled and compiler
gcc". Reorder as `pkg +foo %gcc` to be compatible with Spack v0.x and
v1.0.
>  spack v1.0 support: %foo +bar -> +bar %foo

- post-processing/README.md
- post-processing/plot_handler.py
- post-processing/post_processing.py
- post-processing/test_post_processing.py
Addresses #306 and #307.
- `original` - original df containing all perflog data
- `filtered` - filtered original df containing only relevant rows and columns
- `transformed` - fully filtered and transformed df (i.e. scaling applied etc.)
> Update post-processing outputs
