apps/dirac/README.md

I have addressed most of the comments from PR#2 and modified the readme file accordingly.

Address review comments in #25

---

modules/utils.py

Fix undefined variable error in `identify_build_environment`

---

README.md
modules/utils.py
spack-environments/archer2/compute-node/spack.yaml
spack-environments/common.yaml
spack-environments/cosma8/compute-node/spack.yaml
spack-environments/csd3-icelake/compute-node/spack.yaml
spack-environments/csd3-skylake/compute-node/spack.yaml
spack-environments/dial3/compute-node/spack.yaml
spack-environments/github-actions/default/spack.yaml
spack-environments/isambard/cascadelake/spack.yaml
spack-environments/myriad/compute-node/spack.yaml
spack-environments/tesseract/compute-node/spack.yaml
spack-environments/tursa/cpu/spack.yaml

Also, update the syntax of the concretizer in Spack environments.

Require Spack 0.18

---

spack-environments/isambard-cascadelake/compute-node/spack.yaml

@kaanolgu Can you please try out this environment?  It worked for me to install `libxml2%gcc@9.2.0`

[isambard-cascadelake] Various improvements to Spack environment

---

CONTRIBUTING.md

Add note on how to add a custom spack repo to a custom spack environment for maximum customness

Document custom repo in custom environment

---

.github/workflows/ci.yml
README.md
SYSTEMS.md
benchmarks/apps/cp2k/cp2k.py
benchmarks/apps/dirac/Sphng/sphng.py
benchmarks/apps/dirac/Trove/trove.py
benchmarks/apps/dirac/Trove_pdsyev/pdsyev.py
benchmarks/apps/grid/grid.py
benchmarks/apps/hpgmg/hpgmg.py
benchmarks/apps/legacy/hpcg/reframe_hpcg.py
benchmarks/apps/swift/swift.py
benchmarks/apps/wrf/wrf.py
benchmarks/examples/sombrero/sombrero.py
benchmarks/reframe_config.py
pyproject.toml

Haven't tested thoroughly, but the simple sombrero example works for me for the time being.
Eventually will fix #89.

Upgrade to ReFrame v4

---

benchmarks/examples/sombrero/sombrero.py

[sombrero] Remove call to `sys.path.append`

---

benchmarks/apps/cp2k/cp2k.py
benchmarks/apps/grid/grid.py
benchmarks/apps/hpgmg/hpgmg.py
benchmarks/apps/hpl/hpl.py
benchmarks/apps/imb/imb.py
benchmarks/apps/omb/omb.py
benchmarks/apps/openmm/openmm_rfm.py
benchmarks/apps/sombrero/sombrero.py
benchmarks/apps/swift/swift.py
benchmarks/apps/wrf/wrf.py
benchmarks/examples/sombrero/sombrero.py
benchmarks/modules/utils.py

This reduces the boilerplate code needed to set up a new test.

Set `self.build_system.specs` in base `SpackTest` class

---

CONTRIBUTING.md
benchmarks/apps/openmm/openmm_rfm.py

Add some minimal documention for how to write GPU benchmarks

---

benchmarks/modules/utils.py

~I haven't actually tested this yet, but this gives an idea of how to address the problem of building on the compute node.~  *Edit*: now tested, it's working as expected.   CC: @kaanolgu.

[SpackTest] Force building on compute node with maximum number of CPUs

---

benchmarks/modules/utils.py

Limit build jobs to a maximum of 16

---

benchmarks/apps/hpcg/hpcg.py

We should now be specifying `-gpu` explicitly if GPU is not required.

[hpcg] Fix valid systems

---

benchmarks/spack/csd3-skylake/compute-node/spack.yaml

I forgot to open this PR yesterday.

[csd3-skylake] Add GCC 11 compiler to Spack environment

---

README.md

Renaming "generic" to "default" in README

---

post-processing/README.md
post-processing/post_processing.py
post-processing/post_processing_config.yaml
post-processing/post_processing_tutorial.md
post-processing/test_post_processing.py
pyproject.toml

Add generic plot script for post-processing

---

benchmarks/spack/csd3-cascadelake/compute-node/spack.yaml

Csd3 cascadelake nodes seem to have a new os, updating it in our spack environment

Update csd3-cascadelake OS

---

post-processing/post_processing.py

Allow less than max number of points per series

---

benchmarks/reframe_config.py

Note: I haven't tested this.
Fix #209.

config: always request exclusive nodes on CSD3

---

benchmarks/spack/archer2/compute-node/spack.yaml

Ref https://github.com/ukri-excalibur/excalibur-tests/pull/185#issuecomment-1634458867

Update Spack environment for Archer2

---

README.md

Add documentation on running multiple tests with tags

---

.github/workflows/ci.yml
MANIFEST.in
post-processing/README.md
post-processing/post_processing.py
post-processing/post_processing_config.yaml
post-processing/test_post_processing.py
pyproject.toml

Add proper DataFrame types for post-processing (+ other misc fixes)

---

SYSTEMS.md

Update python requirements on myriad

---

post-processing/config_handler.py
post-processing/streamlit_post_processing.py

Add config upload and download to Streamlit UI for post-processing

---

benchmarks/reframe_config.py

This should solve the problem of spack having to lock files while building and then the lock timing out and failing the build.
I think we saw this problem during the CIUK23 tutorial on ARCHER2.

Add configuration to limit parallel local jobs to 1

---

.github/workflows/docs.yml
docs/post-processing
docs/post-processing/README.md

`apps/` and `post-processing/` are symlinks to the directories in our repository, with the result the website includes *all* the files in them.

[docs] Exclude unrelated files

---

.github/workflows/docs.yml
mkdocs.yml

Based on https://github.com/UCL-RITS/mkdocs-rc-docs/blob/b46ca8eda396ca1b141ef965a34ef94f29530b6a/mkdocs-project-dir/mkdocs.yml#L27-L41

[docs] Enable dark mode

---

post-processing/streamlit_post_processing.py

Forgot to include this as part of #281 yesterday, so now this gets its own PR.

Add invalid config download warning to Streamlit UI for post-processing

---

docs/contributing.md

Add note on spack recipes

---

docs/systems.md
mkdocs.yml

Add system-specific documentation on Cosma

---

post-processing/README.md
post-processing/config_handler.py
post-processing/post_processing.py
post-processing/streamlit_post_processing.py
post-processing/test_post_processing.py

Integrate extra columns into Streamlit UI for post-processing

---

post-processing/config_handler.py
post-processing/plot_handler.py
post-processing/post_processing.py
post-processing/streamlit_post_processing.py

Add scaling and other enhancements to Streamlit UI for post-processing

---

benchmarks/spack/cosma8/compute-node/spack.yaml

Cosma8 Update Configurations and Spack Environments

---

pyproject.toml

Temporarily fixes the issues reported in #345

Fix Streamlit version to something that works, to avoid various weirdness

---

README.md

Update for tutorial link

---

post-processing/streamlit_post_processing.py

Fix visibility for long multiselect labels

---

post-processing/README.md
post-processing/plot_handler.py
post-processing/post_processing.py
post-processing/streamlit_post_processing.py

Add numeric axis log scaling options for post-processing

---

post-processing/README.md
post-processing/config_handler.py
post-processing/streamlit_post_processing.py
pyproject.toml

Upgrades Bokeh and Streamlit versions + fixes some miscellaneous bugs.

Update post-processing to use streamlit-bokeh

---

post-processing/plot_handler.py

Update plot axis scaling label for post-processing

---

post-processing/plot_handler.py
post-processing/post_processing.py
post-processing/streamlit_post_processing.py
post-processing/test_post_processing.py

Streamline Streamlit sidebar UI
